// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RolePlayHelper.DAL.Database;

#nullable disable

namespace RolePlayHelper.DAL.Migrations
{
    [DbContext(typeof(RolePlayHelperContext))]
    [Migration("20251021135540_21-10-25")]
    partial class _211025
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CharClassCharacter", b =>
                {
                    b.Property<int>("CharactersId")
                        .HasColumnType("int");

                    b.Property<int>("ClassesId")
                        .HasColumnType("int");

                    b.HasKey("CharactersId", "ClassesId");

                    b.HasIndex("ClassesId");

                    b.ToTable("Character_Class_Link", (string)null);
                });

            modelBuilder.Entity("LanguageRace", b =>
                {
                    b.Property<int>("LanguagesId")
                        .HasColumnType("int");

                    b.Property<int>("RacesId")
                        .HasColumnType("int");

                    b.HasKey("LanguagesId", "RacesId");

                    b.HasIndex("RacesId");

                    b.ToTable("Race_Languages", (string)null);
                });

            modelBuilder.Entity("RaceRaceTrait", b =>
                {
                    b.Property<int>("RacesId")
                        .HasColumnType("int");

                    b.Property<int>("TraitsId")
                        .HasColumnType("int");

                    b.HasKey("RacesId", "TraitsId");

                    b.HasIndex("TraitsId");

                    b.ToTable("Race_Traits", (string)null);
                });

            modelBuilder.Entity("RolePlayHelper.DL.Entities.CharClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ParentClassId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ParentClassId");

                    b.ToTable("Character_Class", (string)null);
                });

            modelBuilder.Entity("RolePlayHelper.DL.Entities.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArmorClass")
                        .HasColumnType("int");

                    b.Property<int>("CHA")
                        .HasColumnType("int");

                    b.Property<int>("CON")
                        .HasColumnType("int");

                    b.Property<string>("ClassIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DEX")
                        .HasColumnType("int");

                    b.Property<int>("HitModifier")
                        .HasColumnType("int");

                    b.Property<int>("INT")
                        .HasColumnType("int");

                    b.Property<int>("Initiative")
                        .HasColumnType("int");

                    b.Property<int>("MVT")
                        .HasColumnType("int");

                    b.Property<int>("MaxHP")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RaceId")
                        .HasColumnType("int");

                    b.Property<int>("STR")
                        .HasColumnType("int");

                    b.Property<int>("SpellAttack")
                        .HasColumnType("int");

                    b.Property<int>("SpellSave")
                        .HasColumnType("int");

                    b.Property<string>("SubClassIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WIS")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_Character");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("RaceId");

                    b.ToTable("Character", (string)null);
                });

            modelBuilder.Entity("RolePlayHelper.DL.Entities.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Language", (string)null);
                });

            modelBuilder.Entity("RolePlayHelper.DL.Entities.Race", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StatModifierId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_Race");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("StatModifierId")
                        .IsUnique();

                    b.ToTable("Race", (string)null);
                });

            modelBuilder.Entity("RolePlayHelper.DL.Entities.RaceTrait", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("RaceTrait", (string)null);
                });

            modelBuilder.Entity("RolePlayHelper.DL.Entities.StatModifier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArmorClass")
                        .HasColumnType("int");

                    b.Property<int?>("CHA")
                        .HasColumnType("int");

                    b.Property<int?>("CON")
                        .HasColumnType("int");

                    b.Property<int?>("DEX")
                        .HasColumnType("int");

                    b.Property<int?>("HitModifier")
                        .HasColumnType("int");

                    b.Property<int?>("INT")
                        .HasColumnType("int");

                    b.Property<int?>("Initiative")
                        .HasColumnType("int");

                    b.Property<int?>("MVT")
                        .HasColumnType("int");

                    b.Property<int?>("MaxHP")
                        .HasColumnType("int");

                    b.Property<int?>("STR")
                        .HasColumnType("int");

                    b.Property<int?>("SpellAttack")
                        .HasColumnType("int");

                    b.Property<int?>("SpellSave")
                        .HasColumnType("int");

                    b.Property<int?>("WIS")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_StatModifier");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.ToTable("StatModifier", (string)null);
                });

            modelBuilder.Entity("RolePlayHelper.DL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK_User");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("User_", (string)null);
                });

            modelBuilder.Entity("CharClassCharacter", b =>
                {
                    b.HasOne("RolePlayHelper.DL.Entities.Character", null)
                        .WithMany()
                        .HasForeignKey("CharactersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RolePlayHelper.DL.Entities.CharClass", null)
                        .WithMany()
                        .HasForeignKey("ClassesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LanguageRace", b =>
                {
                    b.HasOne("RolePlayHelper.DL.Entities.Language", null)
                        .WithMany()
                        .HasForeignKey("LanguagesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RolePlayHelper.DL.Entities.Race", null)
                        .WithMany()
                        .HasForeignKey("RacesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RaceRaceTrait", b =>
                {
                    b.HasOne("RolePlayHelper.DL.Entities.Race", null)
                        .WithMany()
                        .HasForeignKey("RacesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RolePlayHelper.DL.Entities.RaceTrait", null)
                        .WithMany()
                        .HasForeignKey("TraitsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RolePlayHelper.DL.Entities.CharClass", b =>
                {
                    b.HasOne("RolePlayHelper.DL.Entities.CharClass", "ParentClass")
                        .WithMany("SubClasses")
                        .HasForeignKey("ParentClassId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentClass");
                });

            modelBuilder.Entity("RolePlayHelper.DL.Entities.Character", b =>
                {
                    b.HasOne("RolePlayHelper.DL.Entities.Race", "Race")
                        .WithMany("Characters")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Race");
                });

            modelBuilder.Entity("RolePlayHelper.DL.Entities.Race", b =>
                {
                    b.HasOne("RolePlayHelper.DL.Entities.StatModifier", "StatModifier")
                        .WithOne("Race")
                        .HasForeignKey("RolePlayHelper.DL.Entities.Race", "StatModifierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StatModifier");
                });

            modelBuilder.Entity("RolePlayHelper.DL.Entities.CharClass", b =>
                {
                    b.Navigation("SubClasses");
                });

            modelBuilder.Entity("RolePlayHelper.DL.Entities.Race", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("RolePlayHelper.DL.Entities.StatModifier", b =>
                {
                    b.Navigation("Race");
                });
#pragma warning restore 612, 618
        }
    }
}
